networks:
  ei:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - ei
  ei-noah:
    image: 'ghcr.io/bebore/ei-noah-bot/ei-noah:latest'
    networks:
      - ei
    ports:
      - "5100:5100"
    environment:
      - REDIS_URL=redis://redis
      - DBHOST=host.docker.internal
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5100/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - redis
    extra_hosts:
     - "host.docker.internal:host-gateway"
